gravatar_url: 'http://www.gravatar.com/avatar/'
gravatar_url_ssl: 'https://secure.gravatar.com/avatar/'
gravatar_default: 2
gravatar_rating: G
gravatar_cache: 0
user_picture_default: ''
user_picture_dimensions: 85x85